// +build !ignore_autogenerated

/*
 * Tencent is pleased to support the open source community by making TKEStack
 * available.
 *
 * Copyright (C) 2012-2023 Tencent. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at
 *
 * https://opensource.org/licenses/Apache-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&EtcdCluster{}, func(obj interface{}) { SetObjectDefaults_EtcdCluster(obj.(*EtcdCluster)) })
	scheme.AddTypeDefaultingFunc(&EtcdClusterList{}, func(obj interface{}) { SetObjectDefaults_EtcdClusterList(obj.(*EtcdClusterList)) })
	return nil
}

func SetObjectDefaults_EtcdCluster(in *EtcdCluster) {
	SetDefaults_EtcdCluster(in)
}

func SetObjectDefaults_EtcdClusterList(in *EtcdClusterList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_EtcdCluster(a)
	}
}
